/**
 * TuningSystems.js
 * Mathematical principles of musical pitch, intervals, frequencies, and historical tuning systems.
 */

export const TuningSystems = {
  // A4 reference frequency in Hz
  A4_FREQ: 440.0,
  A4_MIDI: 69,

  // Note names in 12-TET chromatic scale
  NOTE_NAMES: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
  NOTE_NAMES_FLAT: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'],

  /**
   * Convert MIDI note number to frequency in 12-Tone Equal Temperament (12-TET)
   * Formula: f = 440 * 2^((midi - 69) / 12)
   */
  midiToFreq(midi, a4 = 440.0) {
    return a4 * Math.pow(2, (midi - 69) / 12);
  },

  /**
   * Convert frequency in Hz to closest MIDI note number and cents deviation
   */
  freqToMidi(freq, a4 = 440.0) {
    const fractionalMidi = 69 + 12 * Math.log2(freq / a4);
    const roundMidi = Math.round(fractionalMidi);
    const centsDeviation = Math.round((fractionalMidi - roundMidi) * 100);
    return { midi: roundMidi, cents: centsDeviation };
  },

  /**
   * Get note name and octave from MIDI note number (e.g. 60 -> 'C4')
   */
  midiToNoteName(midi, useFlats = false) {
    const noteNames = useFlats ? this.NOTE_NAMES_FLAT : this.NOTE_NAMES;
    const name = noteNames[((midi % 12) + 12) % 12];
    const octave = Math.floor(midi / 12) - 1;
    return `${name}${octave}`;
  },

  /**
   * Calculate interval in cents from a frequency ratio f2 / f1
   * Formula: cents = 1200 * log2(ratio)
   */
  ratioToCents(ratio) {
    return 1200 * Math.log2(ratio);
  },

  /**
   * Calculate frequency ratio from interval in cents
   * Formula: ratio = 2^(cents / 1200)
   */
  centsToRatio(cents) {
    return Math.pow(2, cents / 1200);
  },

  /**
   * Compare 12-TET vs Just Intonation vs Pythagorean tuning for all 12 chromatic scale degrees
   * Base: C = root
   */
  getIntonationComparison(rootMidi = 60, a4 = 440.0) {
    const rootFreq = this.midiToFreq(rootMidi, a4);

    // Just Intonation 5-limit ratios (Ptolemaic intense diatonic / standard Just chromatic)
    const justRatios = [
      { name: 'Unison', ratio: 1 / 1, num: 1, den: 1 },
      { name: 'Minor 2nd', ratio: 16 / 15, num: 16, den: 15 },
      { name: 'Major 2nd', ratio: 9 / 8, num: 9, den: 8 },
      { name: 'Minor 3rd', ratio: 6 / 5, num: 6, den: 5 },
      { name: 'Major 3rd', ratio: 5 / 4, num: 5, den: 4 },
      { name: 'Perfect 4th', ratio: 4 / 3, num: 4, den: 3 },
      { name: 'Tritone (Dim 5th)', ratio: 45 / 32, num: 45, den: 32 },
      { name: 'Perfect 5th', ratio: 3 / 2, num: 3, den: 2 },
      { name: 'Minor 6th', ratio: 8 / 5, num: 8, den: 5 },
      { name: 'Major 6th', ratio: 5 / 3, num: 5, den: 3 },
      { name: 'Minor 7th', ratio: 9 / 5, num: 9, den: 5 },
      { name: 'Major 7th', ratio: 15 / 8, num: 15, den: 8 },
      { name: 'Octave', ratio: 2 / 1, num: 2, den: 1 }
    ];

    // Pythagorean ratios (generated by pure 3:2 fifths reduced to octave)
    const pythagoreanRatios = [
      { name: 'Unison', ratio: 1 / 1, fraction: '1/1' },
      { name: 'Minor 2nd', ratio: 256 / 243, fraction: '256/243' },
      { name: 'Major 2nd', ratio: 9 / 8, fraction: '9/8' },
      { name: 'Minor 3rd', ratio: 32 / 27, fraction: '32/27' },
      { name: 'Major 3rd', ratio: 81 / 64, fraction: '81/64' },
      { name: 'Perfect 4th', ratio: 4 / 3, fraction: '4/3' },
      { name: 'Tritone', ratio: 729 / 512, fraction: '729/512' },
      { name: 'Perfect 5th', ratio: 3 / 2, fraction: '3/2' },
      { name: 'Minor 6th', ratio: 128 / 81, fraction: '128/81' },
      { name: 'Major 6th', ratio: 27 / 16, fraction: '27/16' },
      { name: 'Minor 7th', ratio: 16 / 9, fraction: '16/9' },
      { name: 'Major 7th', ratio: 243 / 128, fraction: '243/128' },
      { name: 'Octave', ratio: 2 / 1, fraction: '2/1' }
    ];

    return justRatios.map((item, index) => {
      const tetCents = index * 100;
      const tetRatio = Math.pow(2, index / 12);
      const tetFreq = rootFreq * tetRatio;

      const justCents = Math.round(this.ratioToCents(item.ratio) * 10) / 10;
      const justFreq = rootFreq * item.ratio;
      const justDiff = Math.round((justCents - tetCents) * 10) / 10;

      const pythRatio = pythagoreanRatios[index].ratio;
      const pythCents = Math.round(this.ratioToCents(pythRatio) * 10) / 10;
      const pythFreq = rootFreq * pythRatio;
      const pythDiff = Math.round((pythCents - tetCents) * 10) / 10;

      return {
        degree: index,
        name: item.name,
        note: this.NOTE_NAMES[index % 12],
        tet: { cents: tetCents, freq: tetFreq },
        just: { cents: justCents, freq: justFreq, ratio: `${item.num}/${item.den}`, diffCents: justDiff },
        pythagorean: { cents: pythCents, freq: pythFreq, ratio: pythagoreanRatios[index].fraction, diffCents: pythDiff }
      };
    });
  },

  /**
   * Calculate the Pythagorean Comma
   * (3/2)^12 vs 2^7
   */
  getPythagoreanComma() {
    const twelveFifthsRatio = Math.pow(3 / 2, 12); // ~129.7463
    const sevenOctavesRatio = Math.pow(2, 7);       // 128
    const commaRatio = twelveFifthsRatio / sevenOctavesRatio; // 531441 / 524288 ~= 1.013643
    const cents = this.ratioToCents(commaRatio); // ~23.46 cents

    return {
      twelveFifthsRatio,
      sevenOctavesRatio,
      commaRatio,
      cents: Math.round(cents * 100) / 100,
      fraction: '531441 / 524288',
      explanation: 'Stacking 12 pure fifths (3:2) overshoots 7 pure octaves (2:1) by ~23.46 cents (nearly a quarter of a semitone!). Equal temperament flattens each fifth by ~2 cents so the circle closes.'
    };
  },

  /**
   * Generate the Harmonic Series frequencies for a given fundamental frequency
   */
  getHarmonicSeries(fundamentalFreq, count = 16) {
    const harmonics = [];
    for (let n = 1; n <= count; n++) {
      const freq = fundamentalFreq * n;
      const ratio = n;
      const centsFromRoot = Math.round(this.ratioToCents(ratio) * 10) / 10;
      const octaves = Math.floor(Math.log2(n));
      const reducedRatio = n / Math.pow(2, octaves);
      const reducedCents = Math.round(this.ratioToCents(reducedRatio) * 10) / 10;

      const tetSemitones = Math.round(centsFromRoot / 100);
      const tetCents = tetSemitones * 100;
      const deviation = Math.round((centsFromRoot - tetCents) * 10) / 10;

      let intervalName = '';
      if (n === 1) intervalName = 'Fundamental (1:1)';
      else if (n === 2) intervalName = 'Octave (2:1)';
      else if (n === 3) intervalName = 'Octave + 5th (3:1)';
      else if (n === 4) intervalName = '2 Octaves (4:1)';
      else if (n === 5) intervalName = '2 Octaves + Maj 3rd (5:1)';
      else if (n === 6) intervalName = '2 Octaves + 5th (6:1)';
      else if (n === 7) intervalName = 'Harmonic 7th (7:1, -31¢ flat)';
      else if (n === 8) intervalName = '3 Octaves (8:1)';
      else if (n === 9) intervalName = '3 Octaves + Maj 2nd (9:1)';
      else if (n === 10) intervalName = '3 Octaves + Maj 3rd (10:1)';
      else if (n === 11) intervalName = 'Tritone / 11th (+51¢ sharp)';
      else if (n === 12) intervalName = '3 Octaves + 5th (12:1)';
      else if (n === 13) intervalName = 'Neutral 6th (-41¢ flat)';
      else if (n === 14) intervalName = 'Harmonic 7th (-31¢ flat)';
      else if (n === 15) intervalName = '3 Octaves + Maj 7th (15:1)';
      else if (n === 16) intervalName = '4 Octaves (16:1)';

      harmonics.push({
        n,
        freq: Math.round(freq * 100) / 100,
        centsFromRoot,
        reducedCents,
        deviation,
        intervalName,
        noteEstimate: this.midiToNoteName(this.freqToMidi(fundamentalFreq).midi + tetSemitones)
      });
    }
    return harmonics;
  },

  /**
   * 24-TET Quarter-tone frequency calculation (used in Arabic Maqam)
   */
  quarterToneToFreq(quarterToneIndex, rootFreq = 261.63) {
    return rootFreq * Math.pow(2, quarterToneIndex / 24);
  }
};
